<template>
   <div class="max-w-screen-md md:mx-auto mx-3">
      <h1 class="text-xl font-bold">Film Junk Glossary</h1>

      <div class="mt-3 mb-6">
         The following is a guide to the many colourful terms, phrases and inside jokes that often turn up on the Film Junk Podcast. The goal is to help new listeners become acquainted with the show’s vast history and unique mythology. If you have any other suggestions for new entries, please send them to
         <a href="mailto:filmjunk@gmail.com">filmjunk@gmail.com</a>.
      </div>

      <p><strong>3Don&#8217;t</strong> &#8211; A potential movement proposed by Dax to avoid 3D movies wherever possible due to dark and blurry visuals and a disappointing overall moviegoing experience.</p>
      <p><strong>4KY (Jelly)</strong> &#8211; A term referring to the phenomenon where one&#8217;s opinion of a movie can be elevated or a particularly bad movie can be made more bearable by watching it in 4K resolution. Also known as the 4K Bump.</p>
      <div class="regularbuttondark floatright"><a href="https://clyp.it/jz2km2ns" target="_blank"> <font-awesome-icon :icon="['fas', 'play']" /> Listen </a></div>
      <p><strong>6 Star Rating</strong> &#8211; A concept introduced by Jay on <a href="http://filmjunk.com/2015/05/05/film-junk-podcast-episode-513-the-avengers-age-of-ultron/">Episode #513: The Avengers: Age of Ultron</a> that would allow each Film Junk host to pick two movies a year that will be awarded a special 6 star rating (out of 5 stars) because they are essentially better than perfect. This rating must be awarded upon initial review and cannot be upgraded after the fact.</p>
      <p><strong>7Up Retro</strong> &#8211; A soft drink often referenced on the show due to its memorable use on an episode of Celebrity Apprentice. Celebrities were required to write a jingle for the product, which is the origin of the sound clip of Dee Snider singing &#8220;7Up Retro&#8230; keepin&#8217; it real!&#8221;.</p>
      <p><strong>700 Club</strong> &#8211; People who donated during the Episode 700 live telethon are referred to as members of the Film Junk 700 Club. This is a reference to the long-running Christian talk show / TV news program of the same name.</p>
      <p><strong>The Accused</strong> &#8211; 1988 drama starring Jodie Foster as a woman who is brutally raped in a bar and then participates in a court trial to bring the perpetrators to justice. Often brought up by Jay in an ironic sense and referred to as a comedy despite its heavy subject matter.</p>
      <p><strong>ADR</strong> &#8211; Short for Additional Dialogue Recording. This is the process of recording new dialogue to add to a movie during post-production, usually to fix audio or story issues or to &#8220;punch up&#8221; humour. Frequently criticized by Frank who seems to be hyperaware of it.</p>
      <p><strong>Albinoman</strong> &#8211; A fictional superhero created by Jay and Sean for a series of old movies in which Sean portrays the title character wearing a white wig and mask.</p>
      <p><strong>Alicia</strong> &#8211; Sean&#8217;s wife. She has appeared on a handful of episodes over the years, often those involving TV discussion.</p>
      <p><strong>Alt Comedy (Alternative Comedy)</strong> &#8211; A style of stand up comedy that is more freeform and less reliant on setups and punchlines, sometimes closer to spoken word, and often performed in coffee shops as opposed to comedy clubs. (Some examples include Marc Maron, Louis C.K. and Patton Oswalt.) Used as a disparaging term by Jay towards most modern comedians who he believes are self-indulgent and try too hard to portray themselves as tortured artists.</p>
      <p><strong>Amiibo</strong> &#8211; Collectible toys produced by Nintendo, many of which are rare and hard to find. Jay often teases Frank for obsessing over them although Sean owns a few as well.</p>
      <p><strong>Anal Cancer</strong> &#8211; In the early days of Film Junk, Jay had a health scare where he suspected he might have anal cancer. On <a href="http://filmjunk.com/2007/09/30/download-film-junk-podcast-for-sept-30-2007/">Episode #137</a>, he recounted in gruesome detail all of the various medical procedures he underwent in order to get checked out.</p>
      <p><strong>Andrew</strong> &#8211; See Huckcity or Andrew James.</p>
      <p><strong>Angular Stool</strong> &#8211; A descriptor Jay used to explain the shape of his bowel movements during his anal cancer scare. Also, an item available at your local Ikea.</p>
      <div class="regularbuttondark floatright"><a href="https://clyp.it/dcs0zowr" target="_blank"> <font-awesome-icon :icon="['fas', 'play']" /> Listen </a></div>
      <p><strong>Apwill Dafoeth</strong> &#8211; Fictional holiday proposed by Frank to celebrate actor Willem Dafoe on April the 4th, poking fun at themed days like Alien Day, Star Wars Day and Back to the Future Day.</p>
      <div class="regularbuttondark floatright"><a href="https://clyp.it/mxyp5smg" target="_blank"> <font-awesome-icon :icon="['fas', 'play']" /> Listen </a></div>
      <p><strong>Archbishop of Animation</strong> &#8211; Listener-elected nickname for Dax due to the fact that he is an animator and loves animated movies.</p>
      <div class="regularbuttondark floatright"><a href="https://clyp.it/ntdeb41t" target="_blank"> <font-awesome-icon :icon="['fas', 'play']" /> Listen </a></div>
      <p><strong>Assembling a BBQ</strong> &#8211; A euphemism for potential distractions when watching movies at home without giving them your full attention. First mentioned during Frank&#8217;s questionable rewatch of Minority Report on <a href="http://filmjunk.com/2013/06/25/film-junk-podcast-episode-423-world-war-z-and-monsters-university/">Episode #423: World War Z and Monsters University</a>.</p>
      <p><strong>Baby Blu</strong> &#8211; Term of endearment for a blu-ray.</p>
      <p><strong>Bald Brotherhood</strong> &#8211; An unspoken bond between men without hair, which sometimes leads Frank and Sean to give bald actors or directors the benefit of the doubt. The phrase was coined by Larry David in an episode of Curb Your Enthusiasm.</p>
      <p><strong>Bald Junk</strong> &#8211; A proposed podcast featuring members of the Film Junk crew discussing issues faced by men without hair. The show would potentially be hosted by Sean, Frank and Zak. (The title is also a play on Ball Junk.)</p>
      <p><strong>Banger</strong> &#8211; A term frequently used by Frank to describe a standout song on a soundtrack.</p>
      <p><strong>Beach Ketchup</strong> &#8211; Ketchup that has been left out in the sun for too long, giving it a sour, vinegar-like taste.</p>
      <p><strong>Beater</strong> &#8211; A cheap, possibly older model TV that is being used &#8220;temporarily&#8221; while waiting for price to come down on a newer, better TV. (see also: Double Beater, Bedroom Beater)</p>
      <p><strong>Beauty Day</strong> &#8211; Jay&#8217;s first feature film, a documentary about Cap&#8217;n Video aka Ralph Zavadil, a Niagara Region celebrity who hosted a cable TV show in the vein of Jackass before Jackass ever existed. Currently available on iTunes and Hulu.</p>
      <p><strong>Bedroom Beater</strong> &#8211; A cheap, possibly older model TV bought specifically for use as a secondary TV in your bedroom to watch movies as you fall asleep. (see also: Beater)</p>
      <p><strong>Beef on Weck</strong> &#8211; A type of sandwich made with roast beef on a kummelweck roll that is a local specialty in Buffalo, New York.</p>
      <p><strong>Bias Lighting</strong> &#8211; A type of lighting (often found in the form of LED light strips) placed behind and around the edge of a TV in order to reduce eye strain and improve perceived picture quality.</p>
      <p><strong>Bim Turton</strong> &#8211; A spoonerism of Tim Burton. (See also: Spoonerism)</p>
      <p><strong>Bit</strong> &#8211; A comedy / showbiz term for a planned part of a comedic performance. Frank often uses this to refer to recurring jokes and segments on the podcast.</p>
      <p><strong>Blart</strong> &#8211; An expression inspired by Paul Blart: Mall Cop that re-imagined the protagonist&#8217;s last name as shorthand for &#8220;blood fart&#8221;.</p>
      <p><strong>Blind Buy</strong> &#8211; Purchasing a movie on DVD or Blu-ray without having seen it previously.</p>
      <p><strong>Bluray.com</strong> &#8211; A popular website for news about Blu-ray releases. Jay frequently refers to their review scores and insists that the site is superior to its competitor, High Def Digest.</p>
      <p><strong>Brutal</strong> &#8211; Terrible, bad, not good. Frequent catch phrase used by Jay.</p>
      <p><strong>The Boardroom</strong> &#8211; A discontinued Film Junk spin-off podcast that used to recap weekly episodes of Celebrity Apprentice. Only one season was recorded for Season 7: Infinity vs. Vortex. Back episodes are available <a href="http://filmjunk.com/category/podcasts/the-boardroom/">here</a>.</p>
      <p><strong>Boffo</strong> &#8211; Weird showbiz term used to refer to strong box office numbers and/or something that is otherwise considered a hit in Hollywood. Believed to have originated with trade publications like Variety.</p>
      <p><strong>Bon Cop Bad Cop</strong> &#8211; Canadian action-comedy that holds the record for highest-grossing Canadian film. Frequently praised by Greg and disparaged by Jay.</p>
      <p><strong>Bumbaclot</strong> &#8211; A Jamaican swear word sometimes used by Jay when adopting a Jamaican accent and persona, especially for VibeCast musical performances. A play on this word also surfaced in the &#8217;80s Fantasy Premium Podcast when discussing the character Burglekutt in Willow.</p>
      <p><strong>Butter Face Blus</strong> &#8211; A term to describe the paradoxical nature of a great movie with horrible Blu-ray cover art (and sometimes vice versa).</p>
      <p><strong>Buying or Selling</strong> &#8211; A lame trope that started on business shows giving stock advice that has somehow made its way onto certain movie podcasts as well. If a particular news item is a good idea and seems likely to result in a successful movie, you would &#8220;buy&#8221; it, otherwise you would want to sell. Sometimes referenced sarcastically on Film Junk.</p>
      <p><strong>Bye Bye Johnny</strong> &#8211; A phrase of unknown origins that Reed&#8217;s father often uses in reference to something that could kill you. Possibly an unintentional mash-up of Bye Bye Birdie and So Long Johnny. First mentioned on <a href="http://filmjunk.com/2019/02/20/film-junk-podcast-episode-696-alita-battle-angel/">Episode #696: Alita: Battle Angel</a> and later revisited on <a href="https://filmjunk.com/2019/05/21/film-junk-podcast-episode-707-john-wick-chapter-3-parabellum/">Episode #707: John Wick: Chapter 3 &#8211; Parabellum</a>.</p>
      <p><strong>Cantankerous</strong> &#8211; Irregular podcast hosted by Jay and Reed (and occasionally Sean) in which Reed&#8217;s peculiarities are questioned and explored. As of 2014, there are no current plans for new episodes because Reed does not think there is enough interest. Back episodes are available <a href="http://filmjunk.com/cantankerous-podcast/">here</a>.</p>
      <p><strong>Cap&#8217;n Video</strong> &#8211; See: Beauty Day.</p>
      <p><strong>Celebrity Apprentice</strong> &#8211; Reality show hosted by Donald Trump where various celebrities compete in challenges to raise money for charity. When a new season is airing, the Film Junk crew often discusses each new episode in detail as a recurring weekly feature on the podcast. These discussions have now been spun off into a separate podcast called The Boardroom. (see also: Donald Trump)</p>
      <p><strong>Chain Reaction</strong> &#8211; Choosing to watch a movie based on its connections to another movie you just watched (ie. same director, actor, genre, etc.). Chain reactions can be accidental or intentional.</p>
      <p><strong>CheapCharts</strong> &#8211; Website that conveniently lists all digital movies currently on sale on iTunes. Helped fuel Jay&#8217;s addiction to digital movie purchases during the COVID-19 pandemic.</p>
      <p><strong>Chian</strong> &#8211; Longtime friend of Sean and Jay and original co-host of the podcast in its initial incarnation as Space Junk. Known for his blunt, often profane responses and love of video games. He was a regular co-host of Space Junk Radio / Film Junk Podcast up until episode #76.</p>
      <p><strong>Child Art</strong> &#8211; Refers to the controversial photographs found in Paul Reubens&#8217; home that were originally considered child pornography but defended as being part of his &#8220;extensive historical art photography collection.&#8221;</p>
      <p><strong>China &amp; Silk</strong> &#8211; A 1984 erotic action thriller that borders on softcore pornography. Owned by and often referenced by Jay. (see also: Vinegar Syndrome)</p>
      <div class="regularbuttondark floatright"><a href="https://clyp.it/zdapyo2l" target="_blank"> <font-awesome-icon :icon="['fas', 'play']" /> Listen </a></div>
      <p><strong>Chirp &#8211; </strong>Canadian slang for trash talking, probably originating from hockey.</p>
      <p><strong>Classitosis</strong> &#8211; An affliction that causes you to give classic films higher ratings than they probably deserve. Originally debuted on <a href="https://filmjunk.com/2014/09/30/film-junk-podcast-episode-484-the-equalizer/">Episode #484: The Equalizer</a>. Sean was accused of having Classitosis on <a href="http://filmjunk.com/2015/05/11/film-junk-podcast-episode-514-maggie/">Episode #514: Maggie</a>. (See also: Criterionitis) (See also: Nostalgiarrhea)</p>
      <p><strong>CLIDVIC</strong> &#8211; Awkward term coined by Roger Ebert referring to movies that follow the Rocky formula. Stands for Climb from Despair to Victory. First referenced by Frank on <a href="https://filmjunk.com/2020/11/18/film-junk-podcast-episode-774-best-of-the-best-holidate/">Episode #774: Best of the Best + Holidate</a>.</p>
      <p><strong>The Cloon / Cloontang</strong> &#8211; Cool nicknames for George Clooney.</p>
      <p><strong>Cloud Laser</strong> &#8211; Intentionally flubbed name of a type of pre-amp often used to boost gain on Shure SM7B mics. The real name is Cloudlifter, although the Film Junk crew actually uses the Triton Fethead instead.</p>
      <div class="regularbuttondark floatright"><a href="https://clyp.it/fnak5qvo" target="_blank"> <font-awesome-icon :icon="['fas', 'play']" /> Listen </a></div>
      <p><strong>Coffee Gate</strong> &#8211; An incident that occurred on <a href="http://filmjunk.com/2014/05/20/film-junk-podcast-episode-466-godzilla/">Episode #466: Godzilla</a> where Frank accidentally spilled some coffee on a Blu-ray that he was returning to Jay and was subsequently reprimanded for it.</p>
      <p><strong>Colin Nun</strong> &#8211; Artist, graphic designer and long-time friend of Frank&#8217;s who designed the Film Junk 700 Club pins. Colin has appeared on <a href="https://filmjunk.com/2019/06/26/film-junk-podcast-episode-712-toy-story-4/">Episode #712: Toy Story 4</a> and <a href="https://filmjunk.com/2019/10/09/film-junk-podcast-episode-725-joker/">Episode #725: Joker</a>.</p>
      <div class="regularbuttondark floatright"><a href="https://clyp.it/25j1vh3s" target="_blank"> <font-awesome-icon :icon="['fas', 'play']" /> Listen </a></div>
      <p><strong>Comedy Scale</strong> &#8211; A method of rating a comedy film devised by Frank where each attempted joke is assigned a positive or negative score, resulting in a running total that indicates the film&#8217;s overall effectiveness. Viewed under this method, a bad joke is worse than no joke at all. Originated in <a href="http://filmjunk.com/2012/09/11/film-junk-podcast-episode-385-vhs-and-side-by-side/">Episode #385: VHS + Side By Side</a>.</p>
      <p><strong>Cooking with Gerry</strong> &#8211; A tongue-in-cheek video podcast hosted by Reed Farrington where he gives instructions for preparing mundane and unappealing meals. Inspired by an old video he self-produced with a VHS camcorder in the &#8217;90s. The original video is available on <a href="https://www.youtube.com/watch?v=Oj9-rS06oVk">YouTube</a> and episode #2 is available <a href="http://filmjunk.com/2010/06/14/cooking-with-gerry-episode-2-poutine/">here</a>.</p>
      <p><strong>Corey</strong> &#8211; See Goon.</p>
      <div class="regularbuttondark floatright"><a href="https://clyp.it/j0reglhx" target="_blank"> <font-awesome-icon :icon="['fas', 'play']" /> Listen </a></div>
      <p><strong>Costco Dog</strong> &#8211; According to Frank, the most delicious hot dogs on the planet can be purchased at Costco.</p>
      <p><strong>Manny Coto</strong> &#8211; Director of the cult horror film Dr. Giggles who has gone on to become a TV producer. Often brought up by Greg in a sense of ironic appreciation for his work.</p>
      <div class="regularbuttondark floatright"><a href="https://clyp.it/nru1a2pt" target="_blank"> <font-awesome-icon :icon="['fas', 'play']" /> Listen </a></div>
      <p><strong>Court of Public Opinion (COPO)</strong> &#8211; When a particular opinion (usually a negative one) about a celebrity or public figure takes hold in the general public as a result of the viral nature of social media, sometimes without solid evidence to back it up. Frank has often railed against the Court of Public Opinion, calling for people to make up their own mind about such matters.</p>
      <p><strong>Crameo</strong> &#8211; When a Hollywood blockbuster franchise attempts to cram in brief, mostly useless appearance from a supporting character as a way of setting up future installments.</p>
      <p><strong>Cream Dream Supreme</strong> &#8211; A movie or news headline that gets Frank particularly excited.</p>
      <p><strong>Creep Catchers</strong> &#8211; Group of amateur vigilantes who attempt to confront and expose sexual predators by posing as underage victims online, not unlike Dateline NBC&#8217;s To Catch a Predator.</p>
      <div class="regularbuttondark floatright"><a href="https://clyp.it/2hotik20" target="_blank"> <font-awesome-icon :icon="['fas', 'play']" /> Listen </a></div>
      <p><strong>Criterionitis</strong> &#8211; A term coined by Frank on <a href="https://filmjunk.com/2014/09/23/film-junk-podcast-episode-483-the-drop/">Episode #483: The Drop</a> that refers to slightly inflated review scores for films that are released via the Criterion Collection. Also jokingly used in reference to the disc rot problem found on select Criterion Blu-rays. (See also: Classitosis) (See also: Nostalgiarrhea)</p>
      <p><strong>Critical Wave &#8211; </strong>See: Riding the Critical Wave</p>
      <p><strong>Cursed Films</strong> &#8211; Jay&#8217;s Shudder documentary series exploring various horror movies that are believed to have been cursed. Sometimes referred to as simply &#8220;Cursed&#8221; since that was the original working title.</p>
      <p><strong>The Curve</strong> &#8211; Shorthand for a curved television, which Jay currently owns and continues to push as the future of TV.</p>
      <p><strong>Cynical Boner</strong> &#8211; Refers to a general sense of cynicism, particularly Sean&#8217;s. The term originated as a play on Sean&#8217;s own claim that he doesn&#8217;t have a cynical bone in his body. Originated on <a href="http://filmjunk.com/2012/11/27/film-junk-podcast-episode-395-silver-linings-playbook/">Episode #395: Silver Linings Playbook + Life of Pi</a>.</p>
      <p><strong>Darth Nameless</strong> &#8211; The first pseudonym used by Reed Farrington during his Film Junk debut in our <a href="http://filmjunk.com/2007/02/22/film-junk-versus-episode-4-star-wars-vs-star-trek/">Star Wars vs. Star Trek video podcast</a>, while wearing a Darth Vader mask. Reed established himself as a contrarian from the very start by choosing Star Wars as the superior franchise.</p>
      <p><strong>Dax</strong> &#8211; See: Dax Gordine.</p>
      <p><strong>Dead Set on Life</strong> &#8211; Canadian cooking / travel show on Viceland hosted by Toronto chef Matty Matheson that Jay worked as a director and producer on.</p>
      <p><strong>The Deakmeister (General)</strong> &#8211; Cinematographer Roger Deakins, best known for his collaborations with The Coen Brothers and, more recently, Denis Villeneuve.</p>
      <p><strong>The Deaner</strong> &#8211; Cinematographer Dean Cundey, best known for his collaborations with John Carpenter, Steven Spielberg and Robert Zemeckis.</p>
      <div class="regularbuttondark floatright"><a href="https://clyp.it/5j4ytkna" target="_blank"> <font-awesome-icon :icon="['fas', 'play']" /> Listen </a></div>
      <p><strong>Definitely a Buy</strong> &#8211; A phrase indicating that a particular product (usually a Blu-ray) is essential and worth purchasing. Originally a catch phrase used by The Food Reviewer, a kid who samples and rates various snack foods on YouTube.</p>
      <p><strong>Demo Disc</strong> &#8211; A Blu-ray that is purchased mainly with the intention of being used to showcase your home theatre video and sound capabilities and to impress your friends and family.</p>
      <p><strong>Deppilepsy</strong> &#8211; The scientific term for Frank&#8217;s love of Johnny Depp and willingness to automatically love any movie he is in. First mentioned on <a href="http://filmjunk.com/2016/02/09/film-junk-podcast-episode-551-hail-caesar/">Episode #551: Hail Caesar!</a>. (See also: TimBurculosis)</p>
      <p><strong>Diab-80s</strong> &#8211; The scientific term for an unhealthy obsession with 1980s nostalgia. First mentioned on <a href="http://filmjunk.com/2016/02/17/film-junk-podcast-episode-552-deadpool/">Episode #552: Deadpool</a>.</p>
      <p><strong>Diablos</strong> &#8211; The name of a demon that possessed Reed and was subsequently exorcised on <a href="http://filmjunk.com/2018/06/27/film-junk-podcast-episode-666-jurassic-world-fallen-kingdom/">Episode #666: Jurassic World: Fallen Kingdom</a>.</p>
      <p><strong>Dialogue Bits</strong> &#8211; A trivia game following the same format as Score Bits, but using clips of dialogue instead of music. First introduced on <a href="https://filmjunk.com/2019/03/26/film-junk-podcast-episode-700-the-dirt-us/">Episode #700: The Dirt + Us</a>. (see also: Score Bits)</p>
      <p><strong>Didn&#8217;t Hate Ain&#8217;t Great</strong> &#8211; A term coined by Dax to describe a movie that is perfectly mediocre.</p>
      <p><strong>Disney Industrial Complex (DIC)</strong> &#8211; Frequently referenced by Zak, this describes Disney&#8217;s drive to dominate the entertainment industry by slowly absorbing all of its competitors.</p>
      <p><strong>DIC Move</strong> &#8211; A term proposed by Nuno for any strong arm tactics and bullying employed by Disney in order to crush their competition.</p>
      <p><strong>Disney Infinity</strong> &#8211; A Disney-themed video game similar to Skylanders that involves collectible figurines. Frank is unashamed in his love for the game (and Disney), but often takes a lot of heat for it.</p>
      <p><strong>Dollar Bill</strong> &#8211; &#8220;Dollar Bill&#8221; Burke is an auctioneer and businessman from Derry, New Hampshire who runs Dollar Bill&#8217;s Auction Outlet and Wholesale Company. He stars in videos advertising the various products they currently have for sale, often while wearing ridiculous costumes. Frank is a huge fan.</p>
      <p><strong>Double Beater</strong> &#8211; Purchasing a second inexpensive TV despite already owning another beater. (see also: Beater)</p>
      <p><strong>Double Dip</strong> &#8211; Any re-release of a movie in a format that has already been available, usually in an unsavoury attempt to make fans buy both versions (ie. a special edition version of a movie that is announced almost immediately after the barebones release is out).</p>
      <p><strong>Double Double</strong> &#8211; A Canadian phrase used when ordering a coffee at Tim Horton&#8217;s with two creams and two sugars.</p>
      <p><strong>Double Parm</strong> &#8211; A food-related joke from Paul Blart: Mall Cop 2 that Frank is particularly fond of.</p>
      <p><strong>DP</strong> &#8211; Director of Photography or Double Penetration.</p>
      <div class="regularbuttondark floatright"><a href="https://clyp.it/e3k03s1c" target="_blank"> <font-awesome-icon :icon="['fas', 'play']" /> Listen </a></div>
      <p><strong>Drama for Drama&#8217;s Sake</strong> &#8211; A vague criticism that Frank often applies to movies where dramatic tension and conflict feel contrived or unrealistic.</p>
      <div class="regularbuttondark floatright"><a href="https://clyp.it/isjr0msw" target="_blank"> <font-awesome-icon :icon="['fas', 'play']" /> Listen </a></div>
      <p><strong>Dredd Head</strong> &#8211; A hardcore fan of Judge Dredd. (see also: Pred Head)</p>
      <p><strong>Drive-In</strong> &#8211; Preferred venue for summer movie viewing, in particular bad movies. For example, the phrase &#8220;I can&#8217;t wait to see that at the drive-in&#8221; indicates that the movie will be bad, but enjoyable in that specific setting. Our local drive-in is the Canview Drive-In in Thorold. (see also: Twisted)</p>
      <p><strong>Dropping Lid</strong> &#8211; Nodding off during a boring movie.</p>
      <p><strong>Dropping Tear</strong> &#8211; Getting misty-eyed or just outright crying during a particularly emotional scene in a movie.</p>
      <p><strong>Dropping Tier</strong> &#8211; Becoming a supporter of Film Junk on Patreon.</p>
      <div class="regularbuttondark floatright"><a href="https://clyp.it/mscgxm3n" target="_blank"> <font-awesome-icon :icon="['fas', 'play']" /> Listen </a></div>
      <p><strong>Drunk John Lasseter</strong> &#8211; A <a href="https://www.youtube.com/watch?v=hwEkzi2IiF0" target="_blank">YouTube video</a> put together by Jay that was inspired by the popular Drunk Jeff Goldblum videos.</p>
      <p><strong>Drunk Uncles</strong> &#8211; A nickname for Dax and Greg when they appear on episodes together, usually for comic book movie reviews.</p>
      <p><strong>Duke of Spook</strong> &#8211; Listener-elected nickname for Jay that refers to his love of horror films as a counterpoint to Frank&#8217;s love of comedy.</p>
      <p><strong>Dempster Diving</strong> &#8211; The act of buying a lower quality type of bread at a grocery store. Frank was accused of buying both Dempster&#8217;s and Wonder Bread when he refused to divulge his personal bread of choice. This was explored further on <a href="https://filmjunk.com/2020/04/02/film-junk-podcast-episode-746-tiger-king/">Episode #746: Tiger King</a>. (see also: Too Personal)</p>
      <p><strong>Dumpster Diving</strong> &#8211; A segment where the Film Junk crew catches up with a movie that was panned upon initial release. First debuted on <a href="https://filmjunk.com/2018/09/10/film-junk-podcast-episode-675-911/">Episode #675: 9/11</a>.</p>
      <p><strong>Durst Burp</strong> &#8211; A tell-tale sign or subtle admission of guilt. A reference to the shocking finale of the HBO documentary series <em>The Jinx</em>.</p>
      <p><strong>Dwane</strong> &#8211; Friend of the show who frequently attends the drive-in and board game nights.</p>
      <p><strong>Dwybecast</strong> &#8211; An episode of the podcast where a primary member is absent but Sean is still present. Typically this line-up has featured Sean, Frank and Dax. (See also: Vibecast)</p>
      <div class="regularbuttondark floatright"><a href="https://clyp.it/tjhtne4k" target="_blank"> <font-awesome-icon :icon="['fas', 'play']" /> Listen </a></div>
      <p><strong>Easy Win</strong> &#8211; A great premise, idea or promising combination of behind-the-scenes talent that should automatically result in a great movie.</p>
      <p><strong>Eddie / Eddy / Edd-uh-ee</strong> &#8211; Nickname for Frank&#8217;s alter ego when he goes off on an angry rant. The name is derived from a sound clip of Frank stumbling over words that Jay sometimes plays.</p>
      <p><strong>Editorializing</strong> &#8211; Used to describe Sean&#8217;s habit of reporting on rumours or partially subjective information as if they are fact.</p>
      <p><strong>Efronaissance</strong> &#8211; The redemption of Zac Efron, formerly known for The Disney Channel&#8217;s <em>High School Musical</em>, who has since become known for raunchy R-rated comedies. The term was coined by Zak on <a href="https://filmjunk.com/2016/07/12/film-junk-podcast-episode-573-the-neon-demon/">Episode #573: The Neon Demon</a>.</p>
      <p><strong>Embers of Mirrim</strong> &#8211; Independently-released video game that Frank acted as lead designer on, now available on Steam, PS4 and Xbox One.</p>
      <div class="regularbuttondark floatright"><a href="https://clyp.it/3b1bpfyj" target="_blank"> <font-awesome-icon :icon="['fas', 'play']" /> Listen </a></div>
      <p><strong>Facehuggers</strong> &#8211; The second phase of the Xenomorph&#8217;s life cycle in the Alien movies. Also, now a slang term for breasts.</p>
      <p><strong>Fan Man</strong> &#8211; A person who is overly enthusiastic about something (ie. movies, pop culture, etc.), but is able to maintain his fandom in a dignified way. After being called a fanboy by Jay, Frank clarified that he is a &#8220;Fan Man&#8221; instead. This has also led to a recurring sound bite on the show that is a quote from The Devil&#8217;s Advocate where Al Pacino says he is a &#8220;fan of man&#8221;.</p>
      <p><strong>Famous Bet</strong> &#8211; There have been many memorable wagers between Film Junk members throughout the years, most of which involve Frank in some way. Some of the more notable ones include the Robocop bet (whether the costume for the Robocop remake would have CG elements or be completely practical), the Birdman bet (whether the opening quote in Birdman misspells the word &#8220;Beloved&#8221;), the Star Wars: The Force Awakens bet (whether Han Solo would die in the movie) and the Krampus bet (over the proper pronunciation of Krampus).</p>
      <p><strong>Reed Farrington</strong> &#8211; The stage name of our friend and former co-worker Gerry, who has become an irregular contributor to the site and podcast. Known for his love of Star Trek and sci-fi in general, in addition to his frugality and his hermit-like lifestyle. Has an intense rivalry with Jay that sometimes gets in the way of their friendship. (See also: Darth Nameless) (See also: Cantankerous)</p>
      <p><strong>Terry Fator</strong> &#8211; Ventriloquist, singer and comedian known for winning America&#8217;s Got Talent. Often mentioned by Jay out of respect for his craft and also the fact that his name is Terry. (See also: Terri/Terry)</p>
      <p><strong>Feast for Thine Eyes</strong> &#8211; Expression of praise from Dax that refers to visual excellence in a film, particularly an animated one.</p>
      <p><strong>Feature Presentation</strong> &#8211; Fictional cover band that Frank and Sean have talked about starting that would perform only music from movie soundtracks. According to Frank, the band would focus more on deep album cuts and obscure songs rather than popular favourites.</p>
      <p><strong>Festival Bump</strong> &#8211; A phenomenon where your perception of a movie is skewed at a film festival screening due to the excitement of the situation, the sense of exclusivity and possible presence of the film&#8217;s director or stars. This usually results in a rating that is more positive than it would otherwise be.</p>
      <p><strong>Find Anything Good In There?</strong> &#8211; What Jay said to a man who was caught breaking into his car as recounted on <a href="https://filmjunk.com/2016/09/27/film-junk-podcast-episode-583-sully-and-hunt-for-the-wilderpeople/">Episode #583: Sully and Hunt for the Wilderpeople</a>. Later proposed by Frank as the name of a reality TV show in the vein of Pawn Stars.</p>
      <p><strong>Fishing with Tom</strong> &#8211; Now-defunct podcast hosted by Jay and Sean focusing on the quirky worldview of Tomas Bajuk, a former star of Jay&#8217;s early films. The title is a play on John Lurie&#8217;s cult TV series Fishing with John and the fact that Tom is a big fishing enthusiast.</p>
      <p><strong>The Fister</strong> &#8211; See: Wally Pfister.</p>
      <p><strong>Five Banger</strong> &#8211; A five-star movie (out of five).</p>
      <p><strong>Force Feeding</strong> &#8211; The act of forcing yourself to like a movie or give it a higher rating than it deserves, whether it is for contrarian reasons or simply to justify the purchase of a movie on Blu-ray.</p>
      <p><strong>Formbx257</strong> &#8211; One of Jay&#8217;s favourite YouTube channels catering to G.I. Joe collectors.</p>
      <p><strong>Four Banger</strong> &#8211; A four-star movie (out of four).</p>
      <p><strong>Franchise Kicks</strong> &#8211; Jay is a fan of this popular YouTuber, known for his unboxing videos, liquidation pallets and reseller tips.</p>
      <p><strong>Frankie Knuckles</strong> &#8211; Frank&#8217;s nickname on the Ball Junk Podcast. A reference to the late DJ and music producer of the same name.</p>
      <p><strong>Frankie Millennium</strong> &#8211; A new nickname for Frank proposed by Jay on <a href="https://filmjunk.com/2019/11/06/film-junk-podcast-episode-729-the-lighthouse/">Episode #729: The Lighthouse</a> mainly because it sounds cool.</p>
      <p><strong>Free Pass</strong> &#8211; Automatically giving a movie a positive review or the benefit of the doubt for superficial reasons (ie. due to the involvement of a respected director, actor, etc.).</p>
      <p><strong>William Friedkin</strong> &#8211; Director of movies like The Exorcist and The French Connection. Sometimes mentioned because of how much he sounds like Donald Trump. He also once <a href="https://twitter.com/williamfriedkin/status/523565362084720640" target="_blank">tweeted</a> that he did not endorse The Exorcist Premium Podcast. (see also: Donald Trump)</p>
      <p><strong>Future Santa</strong> &#8211; Jay&#8217;s term for describing the look of Anthony Hopkins as Odin in Marvel&#8217;s Thor movies.</p>
      <p><strong>G Del T</strong> &#8211; Abbreviated nickname for Hellboy and Pan&#8217;s Labyrinth director Guillermo del Toro. On <a href="http://filmjunk.com/2017/05/22/film-junk-podcast-episode-612-alien-covenant/">Episode #612: Alien: Covenant</a>, Reed was unable to pronounce his full name but then proceeded to butcher the shortened form as well.</p>
      <p><strong>Matt Gamble</strong> &#8211; Row Three contributor and co-host of the podcast Where the Long Tail Ends. Known for engaging in arguments with Jay on the podcast and also via social media.</p>
      <p><strong>Gash Crab</strong> &#8211; A cash grab.</p>
      <p><strong>The Gasman</strong> &#8211; Greg&#8217;s on-air handle when he worked at the radio station 97.7 Htz fm in St. Catharines. It is a play on his last name, Gaspari.</p>
      <p><strong>The Gift</strong> &#8211; Frank&#8217;s self-professed ability to predict the endings of movies. It has also ruined his enjoyment of certain movies, causing him to refer to it as a curse as well.</p>
      <p><strong>Greg Gaspari</strong> &#8211; Long-time co-host of the Film Junk Podcast between 2007 and 2013. He appeared on the majority of episodes from Episode #96 through to #411 and now hosts the Ball Junk Podcast with Frank (more info on his departure <a href="http://filmjunk.com/2013/04/08/so-long-and-thanks-for-all-the-pineapple-soda/">here</a>). (See also: The Gasman)</p>
      <div class="regularbuttondark floatright"><a href="https://clyp.it/f3nsyydk" target="_blank"> <font-awesome-icon :icon="['fas', 'play']" /> Listen </a></div>
      <p><strong>General Theory of Collectibility</strong> &#8211; A term that applies to a Blu-ray collector who values quantity over quality in their collection. (See also: Juicing) (See also: Special Theory of Collectibility) » <a href="https://clyp.it/f3nsyydk" target="_blank">Audio Clip</a></p>
      <p><strong>Genre Film</strong> &#8211; A movie that follows an established formula or set of conventions. Commonly used as a synonym for horror movie or b-movie although the term expands beyond that.</p>
      <p><strong>Gerry</strong> &#8211; See Reed Farrington.</p>
      <p><strong>Ghost</strong> &#8211; Swedish metal band known for their theatrical stage show that makes use of mock satanic imagery. Jay often ribs Frank over his love of the band.</p>
      <p><strong>The Goblin Man of Norway</strong> &#8211; Three-part faux documentary directed by Jay to promote the video game Too Human while he worked at Silicon Knights. (see also: Silicon Knights)</p>
      <div class="regularbuttondark floatright"><a href="https://clyp.it/rgr3t2is" target="_blank"> <font-awesome-icon :icon="['fas', 'play']" /> Listen </a></div>
      <p><strong>Going Clear</strong> &#8211; The act of retrofitting an entire Blu-ray collection with clear cases (also a play on the Scientology term and documentary of the same name). First proposed by Jay on <a href="https://filmjunk.com/2016/12/14/film-junk-bonus-podcast-movie-organization-manifesto-part-5/">Part 5 of the Movie Organization Manifesto</a>.</p>
      <p><strong>Golden Corral</strong> &#8211; A U.S. restaurant chain with a large buffet that Jay is obsessed with.</p>
      <div class="regularbuttondark floatright"><a href="https://clyp.it/ozy0o24p" target="_blank"> <font-awesome-icon :icon="['fas', 'play']" /> Listen </a></div>
      <p><strong>Gooby</strong> &#8211; A 2009 Canadian children&#8217;s film about a little boy and his imaginary friend, a terrifying-looking giant teddy bear. Partially watched on TV by Sean late one night while sick with a fever, thus scarring him for life. First mentioned on <a href="http://http://filmjunk.com/2012/12/04/film-junk-podcast-episode-396-killing-them-softly/">Episode #396: Killing Them Softly</a> and then later revisited on <a href="http://filmjunk.com/2015/02/04/film-junk-podcast-episode-501-a-most-violent-year/">Episode #501: A Most Violent Year</a>.</p>
      <p><strong>Goon</strong> &#8211; Short for Pretentious Goon, the internet handle of Corey Pierce, an illustrator, high school friend of Jay and Chian, long-time contributor to the site and occasional guest on the podcast. Corey also designed the hot dog, poutine, popcorn and pop logo that we used on the podcast for quite a while.</p>
      <p><strong>Dax Gordine</strong> &#8211; An artist and animator who used to work with Sean, Jay and Frank at Silicon Knights. He has been a frequent guest on the podcast, especially when Sean is absent. (See also: Vibecast)</p>
      <p><strong>Gore Hound</strong> &#8211; A fan of violent and bloody horror movies and/or a fan of director Gore Verbinski.</p>
      <p><strong>Matt Gourley</strong> &#8211; L.A.-based actor and comedian who appears on such podcasts as I Was There Too, Superego, James Bonding and The Andy Daly Podcast Pilot Project and has guested on Film Junk. Jay has also appeared on an episode of I Was There Too and directed the short film The Squibbening documenting the fulfillment of Matt&#8217;s lifelong dream to be squibbed.</p>
      <p><strong>Greater sage-grouse</strong> &#8211; Frank&#8217;s favourite type of bird.</p>
      <p><strong>Gregory Allen</strong> &#8211; Greg&#8217;s on-air handle when he worked at an easy listening light rock radio station. It is simply his first and middle name and is the reverse of the the Jonah Hill animated series Allen Gregory.</p>
      <p><strong>Gun Kata</strong> &#8211; The stylized combination of martial arts and gunplay, often shot in slow-motion, that originated from Hong Kong action movies and eventually became overused in Hollywood blockbusters and video games thanks to The Matrix. The actual term Gun Kata comes from Kurt Wimmer&#8217;s 2002 film Equilibrium starring Christian Bale.</p>
      <p><strong>Karnox Legend</strong> &#8211; Brand of gaming chair purchased by Frank around Christmas 2020 and subsequently turned into a soundboard clip often used by Jay.</p>
      <p><strong>Kurt Halfyard</strong> &#8211; Row Three and Twitch contributor who has made several guest appearances on the podcast over the years. Also the man behind The Movie Club Podcast, which members of the Film Junk crew have appeared on many times.</p>
      <p><strong>The Hammer</strong> &#8211; Hamilton, Ontario.</p>
      <p><strong>Helltown</strong> &#8211; Faux documentary-style horror feature written and directed by Jay that aired on Destination America in 2017. He did not have full creative control over it, but he did manage to sneak in several Film Junk-related easter eggs.</p>
      <p><strong>Hessthetic</strong> &#8211; Term coined by Frank that refers to the distinct visual style of films by directed Jared Hess. Originated on <a href="http://filmjunk.com/2016/10/04/film-junk-podcast-episode-584-miss-peregrines-home-for-peculiar-children/">Episode #584: Miss Peregrine&#8217;s Home for Peculiar Children</a>.</p>
      <p><strong>The Het</strong> &#8211; Long-time listener who became known for sending in delightfully vulgar voice mails in the early days of the show.</p>
      <p><strong>High Def Digest</strong> &#8211; See Bluray.com.</p>
      <p><strong>High Density</strong> &#8211; What HD stands for, according to Jay.</p>
      <p><strong>Hollyweird</strong> &#8211; Goofy term for Hollywood based on its reputation for being strange, surreal and insular. Often used ironically by the Film Junk crew.</p>
      <p><strong>Hollyvitz</strong> &#8211; Goofy and not so politically correct term for Hollywood based on its reputation for being run by a lot of Jewish folks. Also sometimes used ironically by the Film Junk crew.</p>
      <div class="regularbuttondark floatright"><a href="https://clyp.it/f25bory0" target="_blank"> <font-awesome-icon :icon="['fas', 'play']" /> Listen </a></div>
      <p><strong>Horror Renaissance</strong> &#8211; An on-going argument about about whether there is a current surge of innovative and inventive new horror films currently being produced over the past few years. Frank strongly disagreed with the idea on <a href="http://filmjunk.com/2015/06/30/film-junk-podcast-episode-521-burying-the-ex/">Episode #521: Burying the Ex</a>.</p>
      <p><strong>Hot Docs</strong> &#8211; Annual documentary film festival in Toronto.</p>
      <div class="regularbuttondark floatright"><a href="https://clyp.it/ohfe1eio" target="_blank"> <font-awesome-icon :icon="['fas', 'play']" /> Listen </a></div>
      <p><strong>Hoverboard</strong> &#8211; A fictional prop in Back to the Future II. A real-life prototype was rumoured to have been made back in the &#8217;80s but that was proven to be a hoax. Frank believed it was real until <a href="http://filmjunk.com/2011/06/07/film-junk-podcast-episode-321-x-men-first-class/">Episode #321: X-Men First Class</a>.</p>
      <p><strong>How to Build a Time Machine</strong> &#8211; Jay&#8217;s second feature-length documentary. Part of the film&#8217;s budget was raised through the Hot Docs DocIgnite crowdsourcing campaign.</p>
      <p><strong>Ron Howard</strong> &#8211; Director of such films as Parenthood, Backdraft and A Beautiful Mind. Frequently scorned by Jay for being a jobber and/or purveyor of Oscar bait. (See also: Jobber, Oscar Bait)</p>
      <p><strong>Huckcity</strong> &#8211; Co-host of the Game Junk Podcast and another former employee of Silicon Knights. His real name is Andrew Hoculik but his nickname comes from the domain name of his personal website (which is amazing).</p>
      <p><strong>Indoctrination</strong> &#8211; The act of trying to influence your children to love the same movies you do, often with the help of toys and books that appeal more to the parents&#8217; nostalgia than to the kids themselves.</p>
      <p><strong>Intox</strong> &#8211; Offered by Jay as an alternative to the Hollywood term &#8220;in talks&#8221;, to be used in situations where an actor or director is rumoured to be in negotiations for a questionable project (and possibly intoxicated). Originated on <a href="https://filmjunk.com/2016/08/16/film-junk-podcast-episode-578-sausage-party/">Episode #578: Sausage Party</a>.</p>
      <p><strong>It is what it is</strong> &#8211; Catch phrase used by Jay that indicates a particular movie does not aspire to be anything more than what it is. Or something like that.</p>
      <p><strong>It&#8217;s Been Awhile</strong> &#8211; 2001 power ballad by the metal band Staind. Whenever someone utters the words &#8220;It&#8217;s been a while&#8221; there is a 50/50 chance Jay will spontaneously break into this song.</p>
      <p><strong>The Jackal</strong> &#8211; Jay&#8217;s alter-ego when hosting a Vibecast. (See also: Vibecast)</p>
      <p><strong>Jackie G</strong> &#8211; Jake Gyllenhaal</p>
      <p><strong>Jackson Square</strong> &#8211; Shopping mall in Hamilton, Ontario where Greg currently works. Frequented by homeless people, drug users, criminals and other undesirables.</p>
      <p><strong>Andrew James</strong> &#8211; Co-host of the Row Three Cinecast and friend of the show. Jay sent Andrew his copy of Mr. Nobody because he couldn&#8217;t stand to keep it on his shelf. (See also: Mr. Nobody)</p>
      <p><strong>Jay Draws</strong> &#8211; A YouTube video series hosted by Jay where he records himself drawing various movie-related characters. Jay also did custom drawings in this style for people who ordered How to Build a Time Machine on Blu-ray.</p>
      <p><strong>J.C. (John Carpenter)</strong> &#8211; Iconic horror director and one of Jay’s favourite filmmakers. A frequent inside joke on the show involves the fact that the Carpenter no longer does anything but play video games and eat fried chicken.</p>
      <p><strong>J.G.L. (Joseph Gordon-Levitt)</strong> &#8211; Actor best known for appearing on 3rd Rock from the Sun who then underwent a career transformation after appearing in such indie films as Mysterious Skin and Brick. Sean is a self-avowed fan of the actor (mainly due to Brick), although over the years it has been exaggerated to become more of a mancrush.</p>
      <p><strong>Jobber</strong> &#8211; A Hollywood filmmaker known for being a hired gun, offering little in the way of creativity or personal style.</p>
      <p><strong>Juicing</strong> &#8211; The act of artificially increasing the size of one&#8217;s movie collection by including kid&#8217;s movies, exercise videos and bargain bin purchases that are never intended to be watched.</p>
      <p><strong>Juice Boxing</strong> &#8211; Increasing the size of one&#8217;s movie collection by purchasing box sets where some or all of the movies are considered undesirable.</p>
      <p><strong>Jump the Dragon</strong> &#8211; Original VibeCast intro song performed and recorded for <a href="http://filmjunk.com/2014/06/17/film-junk-podcast-episode-470-22-jump-street-and-how-to-train-your-dragon-2/">Episode #470: 22 Jump Street and How to Train Your Dragon 2</a>.</p>
      <p><strong>Jumpy</strong> &#8211; Frank&#8217;s term for a horror movie that is full of jump scares, possibly too many to handle while sober.</p>
      <p><strong>Junk Mail</strong> &#8211; A mailbag segment on the podcast where we read and respond to e-mails from listeners and fans.</p>
      <p><strong>Junkers</strong> &#8211; Blanket term for fans and avid listeners of Film Junk.</p>
      <p><strong>The Junkies</strong> &#8211; Annual awards handed out by the Film Junk crew at the end of the year that honour movies in several humourous categories. First appeared on <a href="https://filmjunk.com/2015/01/06/film-junk-podcast-episode-498-inherent-vice-and-best-of-2014/">Episode #498: Inherent Vice and Best of 2014</a>.</p>
      <p><strong>Junky Boys</strong> &#8211; Self-appointed nickname for the Film Junk crew when pulling off prank phone calls on friends. First and only appearance on <a href="https://filmjunk.com/2019/01/02/film-junk-podcast-episode-690-aquaman/">Episode #690: Aquaman</a>.</p>
      <p><strong>Ketchup Chips</strong> &#8211; A delicious flavour of potato chips available only in Canada for some reason.</p>
      <p><strong>King of Comedy (KoC)</strong> &#8211; Title bestowed upon Frank due to his love of comedies, in reference to Martin Scorsese’s 1982 film The King of Comedy. Originated in <a href="http://filmjunk.com/2012/07/16/film-junk-podcast-episode-377-savages/">Episode #377: Savages + Beasts of the Southern Wild</a>.</p>
      <p><strong>King of Conspiracy</strong> &#8211; Title bestowed upon Frank due to his penchant for finding ulterior motives and hidden meanings in everything.</p>
      <p><strong>Krampus</strong> &#8211; The pronunciation of the title of this film led to an infamous and seemingly unending debate that spanned multiple episodes. The actual bet was made between Jay and Sean on <a href="https://filmjunk.com/2015/11/24/film-junk-podcast-episode-541-the-night-before/">Episode #541: The Night Before</a> and settled on <a href="https://filmjunk.com/2015/12/08/film-junk-podcast-episode-543-krampus/">Episode #543: Krampus</a>.</p>
      <p><strong>Kurt</strong> &#8211; See Kurt Halfyard.</p>
      <p><strong>Lawrence Gagner</strong> &#8211; The owner / creator of LG Electronics, according to Jay. In reality, LG actually stands for Lucky Goldstar (created when the company Goldstar merged with Lucky Chemical).</p>
      <p><strong>Letterboxd</strong> &#8211; An online service for logging movies you have watched and sharing ratings, reviews and lists with friends. The fourth installment of the Movie Organization Manifesto includes Frank&#8217;s Ten Commandments for using Letterboxd.</p>
      <p><strong>Letterboxd Police</strong> &#8211; Refers to Frank&#8217;s habit of constantly monitoring Letterboxd and calling people out on inconsistencies in their ratings.</p>
      <p><strong>Library</strong> &#8211; The phrase &#8220;borrowed from the library&#8221; may refer to obtaining a movie through legally questionable means (ie. BitTorrent) or in some cases (as with Huckcity on Game Junk) may actually refer to the local library.</p>
      <p><strong>Life&#8217;s Shit</strong> &#8211; Repurposed slogan and hashtag for LG proposed by Frank after he purchased a defective LG TV and had a poor customer service experience.</p>
      <p><strong>Little House (on the Prairie)</strong> &#8211; TV series from the &#8217;70s and early &#8217;80s starring Michael Landon and Melissa Gilbert. It follows the Ingalls family through the trials and tribulations of frontier life in the late 19th century Midwestern United States. Jay is a huge fan of the show and has often talked about starting his own Little House podcast. (See also: Roseanne)</p>
      <p><strong>Lyin&#8217; Rian</strong> &#8211; Pejorative nickname for Rian Johnson used by haters of Star Wars: The Last Jedi. Often referenced sarcastically by Jay. (see also: Roundhead Rian)</p>
      <p><strong>Ma&#8217;am</strong> &#8211; Abbreviation for madam and a common phrase used in British films to address an older woman. It was the center of a debate due to the pronunciation &#8220;mum&#8221;, which Sean and Frank mistakenly believed was the actual word being used. The debate originated in <a href="http://filmjunk.com/2013/12/20/film-junk-podcast-episode-446-the-hobbit-the-desolation-of-smaug/">Episode #446: The Hobbit: The Desolation of Smaug</a>.</p>
      <p><strong>Manifesto</strong> &#8211; See: Movie Organization Manifesto.</p>
      <p><strong>Marilyn Manson</strong> &#8211; Frank is often teased because he is still a fan of this &#8217;90s shock rocker. (see also: Sport Goth)</p>
      <p><strong>Marquis de Mindfuck</strong> &#8211; Listener-elected nickname for Sean that refers to his love of heady and/or confusing sci-fi movies. (See also: Mindfuck)</p>
      <p><strong>M.A.S.K. </strong>- Short for Mobile Armored Strike Kommand, this is an &#8217;80s cartoon and toy line that Sean was a big fan of as a kid.</p>
      <p><strong>The Master</strong> &#8211; See: Who is The Master?</p>
      <p><strong>Metroidvania</strong> &#8211; Sean&#8217;s favourite style of video game, involving a single interconnected world in which new abilities are slowly acquired or unlocked that allow you to reach new areas. The phrase is an amalgam of Metroid and Castlevania, which Frank disagrees with because Castlevania only adopted this format years later with the release of Castlevania: Symphony of the Night.</p>
      <p><strong>Milk Bubble</strong> &#8211; Jay&#8217;s description of what Vin Diesel’s voice sounds like. Originated in <a href="http://filmjunk.com/2013/05/27/film-junk-podcast-episode-419-fast-furious-6-and-the-hangover-part-iii/">Episode #419: Fast &amp; Furious 6 + Hangover 3</a>.</p>
      <p><strong>Mindfuck</strong> &#8211; A movie that messes with your mind and/or makes your brain hurt. It can be a good thing (presenting a satisfying puzzle, clever plot twist or making you see the world in a new way) or it can be a bad thing (overly complicated and confusing). Sean is drawn to these types of films, for better or worse.</p>
      <p><strong>Mise en Scene</strong> &#8211; French term for the overall visual design of a film, including the cinematography, lighting, composition and arrangement of props on screen. Often brought up as an example of the type of pretentious academic film analysis that is generally avoided on Film Junk. Originated in the junk mail of <a href="http://filmjunk.com/2012/08/07/film-junk-podcast-episode-380-total-recall/">Episode #380: Total Recall</a>.</p>
      <p><strong>The Mist</strong> &#8211; Frank Darabont&#8217;s 2007 film has become a part of Film Junk lore for a couple of reasons. In an early episode, it was revealed that Jay angrily confronted some fellow moviegoers who were laughing and talking during the movie, calling them &#8220;cocksuckers.&#8221; More recently, it became the subject of a heated debate over whether or not the end of the movie can be considered a twist ending. This prompted Frank to coin the phrase, &#8220;The Mist ain&#8217;t a twist.&#8221; (See: <a href="https://filmjunk.com/2017/02/08/film-junk-podcast-episode-599-paterson/">Episode #599: Paterson</a> and <a href="https://filmjunk.com/2017/02/22/film-junk-podcast-episode-600-john-wick-chapter-2/">Episode #600: John Wick: Chapter 2</a>.)</p>
      <p><strong>Mom Mentality</strong> &#8211; A term used by Frank to describe rude behaviour and sense of entitlement that mothers have. Originated in the Lethal Weapon premium podcast, where Frank took issue with a grieving mother blaming Murtaugh for the death of her son.</p>
      <p><strong>Monster</strong> &#8211; Popular energy drink that was introduced to the Film Junk crew by Singe on <a href="https://filmjunk.com/2017/01/31/film-junk-podcast-episode-598-war-on-everyone/">Episode #598: War on Everyone</a>. After Jay jokingly tweeted about it, Monster responded by delivering several free cases and the unofficial sponsorship became a running joke on the show. Listeners have begun referring to episodes after #598 as the Monster Era of Film Junk.</p>
      <p><strong>Mouth Breather</strong> &#8211; Derogatory term for a less discerning, casual moviegoer as coined by Frank.</p>
      <p><strong>Movie Organization Manifesto</strong> &#8211; Film Junk&#8217;s strict set of rules for organizing and maintaining a DVD and Blu-ray collection that was developed over the course of a continuing series of podcasts. To date there have been four installments in the series: <a href="http://filmjunk.com/2011/08/04/film-junk-bonus-podcast-movie-organization-manifesto-part-1/">Part 1</a>, <a href="http://filmjunk.com/2011/09/14/film-junk-bonus-podcast-movie-organization-manifesto-part-2/">Part 2</a>, <a href="http://filmjunk.com/2012/12/09/film-junk-bonus-podcast-movie-organization-manifesto-part-3/">Part 3</a> and <a href="http://filmjunk.com/2014/07/08/film-junk-bonus-podcast-movie-organization-manifesto-part-4/">Part 4</a>.</p>
      <p><strong>The Movie Review Show</strong> &#8211; An early incarnation of the podcast recorded occasionally on an old boombox and cassette tape back when Sean, Jay and Frank were still in elementary school. Four long lost episodes of this show have been found and released in MP3 format: <a href="http://filmjunk.com/2014/04/01/the-movie-review-show-9-june-23rd-1991-robin-hood-prince-of-thieves/">The Movie Review Show #9: Robin Hood: Prince of Thieves</a>, <a href="http://filmjunk.com/2017/04/01/the-movie-review-show-20-feb-21-1992-waynes-world/">The Movie Review Show #20: Wayne&#8217;s World</a>, <a href="http://filmjunk.com/2016/03/31/the-movie-review-show-27-aug-2nd-1992-buffy-the-vampire-slayer/">The Movie Review Show #27: Buffy the Vampire Slayer</a>, and <a href="http://filmjunk.com/2015/03/31/the-movie-review-show-bonus-episode-vhs-buyers-guide/">The Movie Review Show: VHS Buyer&#8217;s Guide</a>.</p>
      <p><strong>Mr. Brooks</strong> &#8211; Infamous 2007 thriller starring Kevin Costner as a serial killer that was ravaged by Jay in his review of the film, despite the fact that many others praised it for being dark and twisted and casting Costner against type.</p>
      <p><strong>Mr. Dressup</strong> &#8211; A Canadian children&#8217;s show that ran from 1967 to 1996 featuring a man who does arts and crafts with his two puppet friends Casey and Finnegan. Similar to Mister Rogers&#8217; Neighborhood, although Frank argued that Mr. Dressup is the superior show on <a href="http://filmjunk.com/2018/06/13/film-junk-podcast-episode-664-hereditary-and-oceans-8/">Episode #664: Heriditary + Ocean&#8217;s 8</a> and <a href="http://filmjunk.com/2018/06/18/film-junk-podcast-episode-665-incredibles-2/">Episode #665: Incredibles 2</a>.</p>
      <p><strong>Mr. Nobody</strong> &#8211; 2009 sci-fi film directed by Jaco Van Dormael and starring Jared Leto that involves chaos theory, quantum mechanics and many other concepts. The film was slammed by Film Junk during our podcast review and created a rivalry of sorts with the Row Three Cinecast, who are big fans of the movie. (See also: Mindfuck)</p>
      <p><strong>Mum</strong> &#8211; See: Ma&#8217;am.</p>
      <p><strong>Mumblecore</strong> &#8211; A filmmaking movement and subgenre of independent films marked by micro budget productions, naturalistic cinematography and improvised dialogue. Prominent purveyors include Joe Swanberg, Andrew Bujalski and The Duplass Brothers.</p>
      <p><strong>Muzak for Cybernetics</strong> &#8211; A music podcast formerly hosted by Sean and Zak that focused on hip hop, indie rock and electronic music. (See also: Zak)</p>
      <p><strong>Doug Nagy</strong> &#8211; Hamilton-based comedian and former co-host of The Movie Blog Audio Edition podcast with John Campea. Previous guest appearances on the Film Junk Podcast include <a href="http://filmjunk.com/2010/12/27/film-junk-podcast-episode-300-true-grit/">Episode #300: True Grit</a>, <a href="http://filmjunk.com/2010/04/05/film-junk-podcast-episode-264-clash-of-the-titans/">Episode #264: Clash of the Titans</a>, <a href="http://filmjunk.com/2009/06/29/film-junk-podcast-episode-224-transformers-revenge-of-the-fallen/">Episode #224: Transformers: Revenge of the Fallen</a> and <a href="http://filmjunk.com/2007/07/08/download-film-junk-podcast-for-july-8th-2007/">Episode #125: Transformers</a>.</p>
      <p><strong>New Frank (aka Nu Frank)</strong> &#8211; A brief phase of enlightenment during which Frank handed out positive reviews to just about every movie he saw as a result of a new positive outlook on life. First started on <a href="http://filmjunk.com/2017/03/14/film-junk-podcast-episode-603-kong-skull-island/">Episode #603: Kong: Skull Island</a> and arguably ended with <a href="http://filmjunk.com/2017/05/29/film-junk-podcast-episode-613-baywatch/">Episode #613: Baywatch</a>.</p>
      <p><strong>Nicecore</strong> &#8211; A subgenre or trend in films that focus on kindness and optimism with minimal conflict, supposedly in response to the election of Donald Trump. Discussed with regards to Ant-Man and the Wasp on <a href="http://filmjunk.com/2018/07/09/film-junk-podcast-episode-668-ant-man-and-the-wasp-three-identical-strangers/">Episode #668: Ant-Man and the Wasp + Three Identical Strangers</a>.</p>
      <p><strong>Rob Niosi</strong> &#8211; One of the subjects of Jay&#8217;s documentary, How to Build a Time Machine, who is building a full-scale replica of the time machine from the 1960 film. He previously worked as an animator on Pee-Wee&#8217;s Playhouse and did the stop motion intro for A Very Gerry Xmas.</p>
      <p><strong>Christopher Nolan Special</strong> &#8211; A special episode of the Film Junk podcast focusing on the films of Christopher Nolan that was lost for period of time before being recovered and released just prior to the release of The Dark Knight in 2010.</p>
      <p><strong>Nolanoscopy</strong> &#8211; An uncomfortable examination recommended for any film fan who has become blinded by their admiration for Christopher Nolan (ie. Frank).</p>
      <p><strong>Noodles</strong> &#8211; Guitarist for The Offspring, one of Frank&#8217;s favourite bands. Jay often teases him for liking the band. The term &#8220;Noodlehead&#8221; has since been used to refer to fans of The Offspring on the podcast. (see also: Wet Noodle)</p>
      <p><strong>Nostalgiarrhea</strong> &#8211; A condition that forces someone to blindly love older movies that they watched as a kid due to the nostalgia factor. (See also: Criterionitis) (See also: Classitosis) (see also: Diab-80s)</p>
      <p><strong>Nothing But Trouble</strong> &#8211; Notorious 1991 box office bomb directed by Dan Aykroyd and starring Aykroyd, Chevy Chase, John Candy and Demi Moore. One of Frank&#8217;s favourite films of all time.</p>
      <p><strong>Nuno</strong> &#8211; Artist, illustrator and friend of the show. Has guested on several episodes and also designed the old communist propaganda style podcast logo and the Reed Farrington drawing that was available on t-shirts at one point.</p>
      <p><strong>On Cinema</strong> &#8211; A comedic film review web series hosted by Tim Heidecker (of Tim and Eric fame) and Gregg Turkington. The show is a parody of online movie critics and at times has seemed uncomfortably similar to Film Junk.</p>
      <p><strong>Oreo Madness</strong> &#8211; An interracial pornographic film viewed by a young Jay Cheel at a friend&#8217;s birthday party, as described in the unearthed <a href="http://filmjunk.com/2014/04/01/the-movie-review-show-9-june-23rd-1991-robin-hood-prince-of-thieves/">Episode #9 of The Movie Review Show</a>.</p>
      <p><strong>Oscar Bait</strong> &#8211; A formulaic and often overly sentimental movie that is released between September and December in an obvious bid for Oscar contention.</p>
      <p><strong>Oscarbation</strong> &#8211; The act of hyping up Oscar Bait.</p>
      <p><strong>Outlanders</strong> &#8211; 2007 drama mistakenly watched by Greg instead of the 2008 sci-fi viking film Outlander, as heard on <a href="http://filmjunk.com/2009/03/02/film-junk-podcast-episode-209-outlander/">Episode #209: Outlander</a>.</p>
      <p><strong>Pacific Mall</strong> &#8211; An Asian shopping mall in Markham, north of Toronto. Has been raided multiple times for stores that sell counterfeit merchandise and bootleg movies.</p>
      <p><strong>Part Time</strong> &#8211; A well-known quote from Indiana Jones and the Kingdom of the Crystal Skull that was mocked by Jay in the Indiana Jones premium podcast for Harrison Ford&#8217;s lacklustre delivery. (See also: Ragtime)</p>
      <p><strong>Peach</strong> &#8211; Frank&#8217;s very polite term of endearment for an attractive woman.</p>
      <p><strong>Pen Centre (The Pen)</strong> &#8211; Shopping mall in St. Catharines, Ontario. Pen is short for peninsula, as in the Niagara Peninsula.</p>
      <p><strong>The Pfister</strong> &#8211; See: Wally Pfister.</p>
      <p><strong>Phil May Kermode</strong> &#8211; A fictional film industry maven who is said to be responsible for the creation of the Filmmaker Mode feature on Smart TVs. First mentioned on <a href="https://filmjunk.com/2019/09/04/film-junk-podcast-episode-721-ready-or-not/">Episode #721: Ready or Not</a>.</p>
      <p><strong>The Philosophy of&#8230;</strong> &#8211; Somewhat questionable series of non-fiction books that use popular movies and TV shows as a way of teaching various ideas and topics in modern philosophy. Often brought up as a way of poking fun at Sean, who owns The Philosophy of The Matrix.</p>
      <p><strong>Pineapple Soda</strong> &#8211; An exotic flavour of soda usually only found in the United States that Greg is particularly fond of.</p>
      <p><strong>Pink Slip</strong> &#8211; Similar to a nip slip, but with female genitalia being accidentally exposed instead of nipples.</p>
      <p><strong>Pizza Throat</strong> &#8211; The phenomenon of excess phlegm being caught in the throat after eating pizza, impeding speech and prompting frequent throat clearing. Originated in <a href="http://filmjunk.com/2014/10/27/film-junk-podcast-episode-488-the-town-that-dreaded-sundown-and-pumpkinhead/">Episode #488: The Town That Dreaded Sundown and Pumpkinhead</a>.</p>
      <p><strong>Pleeeease</strong> &#8211; Obscure quote from Men in Black that no one remembers except for Frank, who insists that it is one of the funniest parts of the movie. Often used as a reference point for Frank&#8217;s love of obscure things. Originated in <a href="http://filmjunk.com/2012/05/28/film-junk-podcast-episode-370-men-in-black-3-and-battleship/">Episode #370: Men In Black 3 + Battleship</a>.</p>
      <p><strong>Plop Synopsis</strong> &#8211; An in-depth review or description of a bowel movement.</p>
      <p><strong>Polkaroo</strong> &#8211; A character from the Canadian children&#8217;s TV show Polka Dot Door that would show up at the end of each episode played by one of the actors in costume, only for them to return afterward having just missed him. Referenced by Frank in a spoiler discussion about Tully on <a href="http://filmjunk.com/2018/07/25/film-junk-podcast-episode-670-sorry-to-bother-you/">Episode #670: Sorry to Bother You</a>.</p>
      <p><strong>Pop</strong> &#8211; The Canadian way of saying “soda”.</p>
      <p><strong>Pop on That</strong> &#8211; To purchase something.</p>
      <p><strong>Poutine</strong> &#8211; French-Canadian dish consisting of french fries covered in gravy and cheese curds. Often consumed at the drive-in, where it is known to make movies seem better than they really are.</p>
      <p><strong>Pred Head</strong> &#8211; A hardcore fan of The Predator. (see also: Dredd Head)</p>
      <p><strong>Prescribing Frank</strong> &#8211; An irregular segment on the podcast where Frank is forced to watch older films based primarily on Jay&#8217;s recommendation and report back on them. Debuted on <a href="http://filmjunk.com/2014/09/30/film-junk-podcast-episode-484-the-equalizer/">Episode #484: The Equalizer</a>. (See also: Criterionitis)</p>
      <p><strong>Prescription</strong> &#8211; A recommendation and/or forced viewing of a film you wouldn&#8217;t normally be interested in with the goal of opening your mind to something new.</p>
      <p><strong>Prewatch</strong> &#8211; A term coined by Frank that refers to the research and preparation before watching a movie, a period during which he decided he would change his star rating for Mad Max: Fury Road. Originated on <a href="http://filmjunk.com/2015/09/15/film-junk-podcast-episode-531-the-visit/">Episode #531: The Visit</a>.</p>
      <p><strong>Projuicer</strong> &#8211; A well-known director or celebrity who takes an executive producer credit on a movie in order to help sell it, despite a complete lack of creative involvement. Originated on <a href="http://filmjunk.com/2017/05/03/film-junk-podcast-episode-609-free-fire-and-the-circle/">Episode #609: Free Fire and The Circle</a>.</p>
      <p><strong>Puke Lerry</strong> &#8211; A spoonerism of Luke Perry. (See also: Spoonerism)</p>
      <p><strong>Ragtime</strong> &#8211; A variation or riff on the Indiana Jones &#8220;part time&#8221; quote. (see also: Part Time)</p>
      <p><strong>Ralph</strong> &#8211; See: Beauty Day.</p>
      <p><strong>Rant Alert</strong> &#8211; On early episodes of the podcast, whenever someone on the show (usually Jay) launched into an angry tirade, a siren sound effect would be played to poke fun at them.</p>
      <p><strong>Rapping Granny</strong> &#8211; An example of lowest common denominator humour that is often referenced on the show in a negative way, especially in reference to easy and predictable jokes. The original rapping granny is Ellen Albertini, who performed &#8220;Rapper&#8217;s Delight&#8221; in the Adam Sandler movie The Wedding Singer.</p>
      <p><strong>Rate Bait</strong> &#8211; Awarding a film an extremely high or low score for the purposes of making a statement and/or just to be a troll. First mentioned in the <a href="http://filmjunk.com/2014/05/21/film-junk-premium-podcast-29-godzilla/">Godzilla premium podcast</a>.</p>
      <p><strong>Real Steel</strong> &#8211; 2011 sci-fi film directed by Shawn Levy and starring Hugh Jackman about a man who trains a robot boxer with the help of his son. Sean claimed to have teared up during the film and was subsequently chastised for it.</p>
      <p><strong>Reed&#8217;s House</strong> &#8211; Short video shot by Jay and hosted by Sean where Reed Farrington&#8217;s home and extensive Star Trek collection is explored and revealed to the world. The video can be viewed <a href="http://filmjunk.com/2009/05/11/cantankerous-episode-7-reeds-house-a-video-tour/">here</a>.</p>
      <p><strong>Repair the Hair</strong> &#8211; An addendum to the &#8220;Retain the Grain&#8221; rule asserting that any hair or other defects found in a film&#8217;s original negative can and should be removed during a restoration since they are accidental elements that were never intended by the director.</p>
      <p><strong>Retain the Grain</strong> &#8211; Jay&#8217;s general rule of thumb or mantra when it comes to restoring older movies. While some fans prefer to see film grain completely removed from high-definition transfers, Jay feels that the grain is an important part of how the movie was meant to be seen.</p>
      <p><strong>(Uncle Frank&#8217;s) Retro Lounge</strong> &#8211; A room in Frank’s house that contains his retro video game collection and several old game consoles.</p>
      <p><strong>Riding the Critical Wave</strong> &#8211; A term Frank and Jay often use when accusing Sean of keeping his review scores in line with the general critical consensus for fear of reprisal from the CoPo.</p>
      <p><strong>Rob</strong> &#8211; See: Rob Niosi.</p>
      <p><strong>Roll Up the Rim to Win</strong> &#8211; An annual promotion held by Tim Horton&#8217;s where the rims of their coffee cups contain messages indicating whether or not you have won a prize. (see also: Tim Horton&#8217;s)</p>
      <p><strong>Roman</strong> &#8211; Friend of the show who has previously guested on the podcast and is a producer on many of Jay’s films.</p>
      <p><strong>Roseanne</strong> &#8211; Popular sitcom that aired from 1988 to 1997 starring Roseanne Barr and John Goodman. One of Jay&#8217;s favourite shows of all time. There has been a running joke for many years that Jay wants to start a Roseanne podcast but it still hasn&#8217;t happened yet. (See also: Little House on the Prairie)</p>
      <p><strong>Rose City</strong> &#8211; Welland, Ontario.</p>
      <p><strong>Roundhead Rian</strong> &#8211; Pejorative nickname for Rian Johnson used by haters of Star Wars: The Last Jedi. Often referenced sarcastically by Jay. (see also: Lyin&#8217; Rian)</p>
      <p><strong>Sacrificial Lambs</strong> &#8211; An elaborate conspiracy theory put forth by Frank where big studios like Disney give A-list directors money and freedom to make passion projects that they know will fail (or that the studios purposely sabotage) in order to keep the director in check. They also give critics an opportunity to slam a big budget movie while reserving praise for more valuable franchise properties instead.</p>
      <p><strong>The Scarf</strong> &#8211; Frank&#8217;s nickname for Steven Spielberg, particularly when questioning the quality of his recent work, in reference to a fashion accessory he started wearing in the early 2010s. Perhaps also a riff on the widely used Spielberg nickname The Beard.</p>
      <p><strong>Serviceable</strong> &#8211; A term used to describe a movie that is just okay. It gets the job done but it fails to generate much excitement.</p>
      <p><strong>Score Bits</strong> &#8211; A trivia game that debuted in <a href="http://filmjunk.com/2014/07/01/film-junk-podcast-episode-472-transformers-age-of-extinction/">Episode #472: Transformers: Age of Extinction</a> where movies are guessed based on brief clips of their soundtracks. It has since re-appeared on <a href="http://filmjunk.com/2015/03/24/film-junk-podcast-episode-508-black-sea/">Episode #508: Black Sea</a>, <a href="http://filmjunk.com/2015/06/30/film-junk-podcast-episode-521-burying-the-ex/">Episode #521: Burying the Ex</a> (a special James Horner memorial edition), <a href="http://filmjunk.com/2017/08/02/film-junk-podcast-episode-622-atomic-blonde-and-hans-zimmer-live/">Episode #622: Atomic Blonde and Hans Zimmer Live</a> (Hans Zimmer edition) and <a href="http://filmjunk.com/2018/04/17/film-junk-podcast-episode-656-a-quiet-place/">Episode #656: A Quiet Place</a>. (see also: Dialogue Bits)</p>
      <p><strong>Scott</strong> &#8211; Singe&#8217;s former work partner and fellow police officer. Known for being an afficionado of Japanese culture. First appeared on <a href="https://filmjunk.com/2016/01/26/film-junk-podcast-episode-549-13-hours-the-secret-soldiers-of-benghazi/">Episode #549: 13 Hours: The Secret Soldiers of Benghazi</a>.</p>
      <p><strong>The Seandolorian</strong> &#8211; A fictional TV show about Sean&#8217;s life proposed by Jay on <a href="https://filmjunk.com/2020/12/22/film-junk-podcast-episode-779-the-mandalorian-season-2/">Episode #779: The Mandalorian: Season 2</a>.</p>
      <p><strong>Set Piece</strong> &#8211; Usually refers to an elaborate action scene in a movie that requires a lot of planning to pull off. Can also be used in a more general way to refer to a highlight or key moment in a movie.</p>
      <p><strong>Shame Drawer</strong> &#8211; A place to store and keep out of sight any Blu-rays in your collection that do not abide by the Movie Organization Manifesto.</p>
      <p><strong>Sigourney&#8217;s Weaver</strong> &#8211; A Reed Farrington blunder that came to be used as slang for the female genitalia.</p>
      <p><strong>Singe</strong> &#8211; Friend of the show and former frequent guest on Sean and Jay&#8217;s university radio show who is now a police officer. Known for telling amusing work-related stories during his rare guest appearances on the podcast. Appearances include Episode #155, Episode #160 and <a href="http://filmjunk.com/2009/12/21/film-junk-podcast-episode-248-avatar/">Episode #248: Avatar</a>.</p>
      <p><strong>Site A</strong> &#8211; Code name for the original Film Junk recording studio at Sean&#8217;s house.</p>
      <p><strong>Site B</strong> &#8211; Code name for the secondary recording studio at Frank&#8217;s house, inspired by the setting of The Lost World: Jurassic Park, Isla Sorna (also known as Site B).</p>
      <p><strong>Site C</strong> &#8211; Code name for the third recording studio at Jay&#8217;s house.</p>
      <p><strong>S.K. (Silicon Knights)</strong> &#8211; A video game company based in St. Catharines, Ontario where Sean, Jay, Frank, Reed, Dax, Chian and Huckcity all used to work.</p>
      <p><strong>Sloan</strong> &#8211; Canadian rock band originally from Halifax, Nova Scotia, formed in the early &#8217;90s and still together today. One of Sean and Frank’s favourite bands.</p>
      <p><strong>Smoke Show</strong> &#8211; An attractive woman.</p>
      <p><strong>S.O.S. Fantomes</strong> &#8211; The French title of Ghostbusters, singled out as an example of ugly French translations often found on Canadian DVD and Blu-ray releases. Originated in <a href="http://filmjunk.com/2009/06/23/film-junk-podcast-episode-223-year-one/">Episode #223: Year One</a>.</p>
      <p><strong>Soundboard</strong> &#8211; After episode 700, the Film Junk crew upgraded to a Rodecaster Pro mixing board with a built-in soundboard allowing for the live playback of short sound clips and music. This has helped to usher in a whole new era for anti-entertainment for the podcast.</p>
      <p><strong>Space Junk</strong> &#8211; Original name of the website and podcast when it launched in the early 2000s and covered music and video games in addition to film. Now occasionally used as a moniker for our entire Junk-related podcast network.</p>
      <div class="regularbuttondark floatright"><a href="https://clyp.it/f3nsyydk" target="_blank"> <font-awesome-icon :icon="['fas', 'play']" /> Listen </a></div>
      <p><strong>Special Theory of Collectibility</strong> &#8211; A term that applies to a Blu-ray collector who values quality over quantity in their collection. (See also: General Theory of Collectibility)</p>
      <p><strong>Spoonerism</strong> &#8211; Play on words in which the first letters of two words are switched around. Jay is known for doing this quite frequently, often by accident.</p>
      <p><strong>Sport Goth</strong> &#8211; Also known as Health Goth. A subculture / fashion trend involving jocks who wear all black sports apparel. Frank is sometimes referred to as a Sport Goth because he often wears sports gear but is also a fan of Marilyn Manson.</p>
      <p><strong>Spot Check</strong> &#8211; To briefly watch and skim through a Blu-ray or 4K disc just to verify that it meets expected visual standards.</p>
      <p><strong>Stag and Doe</strong> &#8211; A primarily Canadian custom where a bride and groom throw a party prior to their wedding to raise money for said wedding by selling booze, playing gambling games, etc. Dax told a story about attending a stag and doe with Frank on <a href="http://filmjunk.com/2018/07/09/film-junk-podcast-episode-668-ant-man-and-the-wasp-three-identical-strangers/">Episode #668: Ant-Man and the Wasp + Three Identical Strangers</a>.</p>
      <p><strong>Star Wars Rocks</strong> &#8211; Star Wars poster hanging in Sean&#8217;s office featuring Star Wars characters playing on stage as a rock band. Often referenced mockingly on the podcast.</p>
      <p><strong>Stop Motion Sickness</strong> &#8211; The scientific term for a disease that causes someone to become obsessed with stop-motion animated films.</p>
      <p><strong>Storyteller</strong> &#8211; A pet peeve of Frank&#8217;s related to the fact that many filmmakers like to humbly refer to themselves as simply &#8220;storytellers&#8221; in interviews.</p>
      <p><strong>Stunt Casting</strong> &#8211; The act of hiring celebrities or actors who may not necessarily be right for a role, simply in order to attract attention. In the past it has also referred to hiring A-list actors for smaller roles usually reserved for character actors. (see also: The Wire Stunt Casting)</p>
      <p><strong>T-Bone Surprise</strong> &#8211; A sudden and shocking car collision where one car slams into another from the side. Winner of our 2014 Moratorium Award on <a href="http://filmjunk.com/2015/01/06/film-junk-podcast-episode-498-inherent-vice-and-best-of-2014/">Episode #498: Inherent Vice and Best of 2014</a>.</p>
      <p><strong>Tanning Chatum</strong> &#8211; A spoonerism of Channing Tatum, used so frequently that we can no longer remember which one is his actual name. (See also: Spoonerism)</p>
      <p><strong>Televisual</strong> &#8211; Adjective frequently used by Jay to describe and criticize the look of Marvel movies and a lot of big blockbusters that have bland, digital and brightly lit visuals (thus looking more like TV shows than movies).</p>
      <p><strong>Terri / Terry</strong> &#8211; A name that Jay frequently brings up in reference to cult &#8217;80s musician Jan Terri.</p>
      <p><strong>That&#8217;s Entertainment</strong> &#8211; A video rental store in St. Catharines, Ontario, that has somehow managed to remain in business all these years by becoming more of a flea market than anything else.</p>
      <p><strong>They Came From Beyond</strong> &#8211; A sci-fi themed instrumental surf band that Jay and Sean used to be in together.</p>
      <p><strong>TimBurculosis (TB)</strong> &#8211; An unhealthy obsession with the films of Tim Burton, to the point where the afflicted person may even try to defend his recent output. Frank is a self-admitted sufferer and coined the term on <a href="http://filmjunk.com/2016/03/22/film-junk-podcast-episode-557-pee-wees-big-holiday/">Episode #557: Pee-wee&#8217;s Big Holiday</a>.</p>
      <p><strong>TIFF</strong> &#8211; The Toronto International Film Festival.</p>
      <p><strong>Tim Horton&#8217;s</strong> &#8211; A popular chain of donut and coffee shops across Canada. Both St. Catharines and Hamilton are particularly dominated by these stores, since both claim to be the &#8220;donut capital of the world.&#8221;</p>
      <p><strong>Tim Tams</strong> &#8211; Delicious chocolate biscuits from Australia that Jay has often requested from listeners down under.</p>
      <p><strong>The Toddfather</strong> &#8211; Nickname for Todd McFarlane, creator of Spawn. Jay has often talked about watching his live drawing videos.</p>
      <p><strong>Tom</strong> &#8211; See: Fishing with Tom.</p>
      <p><strong>Too Personal</strong> &#8211; A sarcastic response sometimes heard on the show when a particular host is uncomfortable answering a question or sharing some personal information. Frank originally uttered this when asked about his bread of choice and it soon became a running joke. (see also: Dempster Diving)</p>
      <p><strong>Toque</strong> &#8211; Canadian word for a specific type of winter hat. Pronounced &#8220;tuke&#8221;.</p>
      <p><strong>Trailer Trash</strong> &#8211; A segment of the podcast where recent trailers for upcoming movies are discussed. It has since been merged with a general news segment.</p>
      <p><strong>The Trews</strong> &#8211; Canadian rock band from Antigonish, Nova Scotia. One of Greg&#8217;s favourite bands, but often disparaged by Jay.</p>
      <p><strong>Trilogy Cred</strong> &#8211; A term coined by Frank throughout many premium podcasts as a method of judging the merit of a particular series of films based on their consistency in terms of style and creative vision across multiple movies.</p>
      <p><strong>Donald Trump</strong> &#8211; American real estate mogul and host of Celebrity Apprentice. Also, now the President of the United States. Jay and Frank used to take turns impersonating Trump on the show. (see also: Celebrity Apprentice) (see also: William Friedkin)</p>
      <p><strong>Jon Turtletaub</strong> &#8211; Director of such films as 3 Ninjas, Cool Runnings and National Treasure. Sometimes brought up as an example of a jobber, although Frank defends him due to his association with Disney films. Often sarcastically referred to as &#8220;visionary director Jon Turtletaub&#8221; in reference to the trailer for The Sorcerer&#8217;s Apprentice. (See also: Jobber)</p>
      <p><strong>Trypophobia</strong> &#8211; A fear of or discomfort with irregular patterns or clusters of small holes or bumps. Jay discusses his realization that he has this phobia on <a href="http://filmjunk.com/2017/09/19/film-junk-podcast-episode-628-mother-and-tiff-2017/">Episode #628: mother! and TIFF 2017</a>. He believes it originated from seeing Richard Pryor&#8217;s piranha-attacked jumper in The Toy as a child.</p>
      <p><strong>Twisted</strong> &#8211; Short film directed by Jay exploring the urban legend that a tornado hit the Canview Drive-In while it was showing the movie Twister. Currently available on <a href="https://vimeo.com/blog/post/staff-pick-premiere-twisted" target="_blank">Vimeo</a>.</p>
      <p><strong>Uncle Terry</strong> &#8211; Jay&#8217;s uncle Terry may or may not have raped a prostitute. He is also the director of Uncle Terry&#8217;s The Shining.</p>
      <p><strong>Vadering</strong> &#8211; A term coined by Dax for falling asleep and breathing heavily during a Star Wars movie. First introduced on <a href="http://filmjunk.com/2016/12/20/film-junk-podcast-episode-592-rogue-one-a-star-wars-story/">Episode #592: Rogue One: A Star Wars Story</a>.</p>
      <p><strong>Vamping</strong> &#8211; A showbiz / broadcasting term that means to stall for time inconspicuously.</p>
      <p><strong>Versus</strong> &#8211; An irregular segment on the podcast where we would take two movie-related things and pit them against each other, debating both sides and then eventually picking a winner. Also the premise of a short-lived series of Film Junk video podcasts.</p>
      <p><strong>A Very Gerry Xmas</strong> &#8211; A holiday-themed short film directed by Jay and starring Reed Farrington.</p>
      <p><strong>Veto</strong> &#8211; A concept introduced to the podcast in 2019 allowing each member of the Film Junk crew to individually skip out on a main review up to 5 times per year while the other two members still review that movie (usually with a guest). The idea is to avoid forcing people to see movies they have no interest in, resulting in more productive discussions. Initially proposed on <a href="https://filmjunk.com/2019/01/16/film-junk-podcast-episode-692-vice/">Episode #692: Vice</a> and first used on <a href="https://filmjunk.com/2019/03/12/film-junk-podcast-episode-699-captain-marvel/">Episode #699: Captain Marvel</a>.</p>
      <p><strong>Vibecast</strong> &#8211; An episode of the Film Junk podcast where Sean is absent, so named for the laidback atmosphere and general resistance to staying on topic. Vibecast episodes have also been known to kick off with an original song performed by the Vibecast crew themselves. (See also: The Jackal)</p>
      <p><strong>Vinegar Syndrome</strong> &#8211; Boutique Blu-ray distributor specializing in obscure genre films. Often praised by Jay despite the fact that many of their titles are essentially softcore porn (ie. <em>China &amp; Silk</em> and <em>Sex World</em>).</p>
      <p><strong>VOD Trash</strong> &#8211; Frank&#8217;s term for low budget VOD releases, most of which usually end up being (in his eyes) significantly inferior to big budget theatrical releases.</p>
      <p><strong>Wally Pfister</strong> &#8211; Christopher Nolan&#8217;s long-time cinematographer and the director of Transcendence. Frank is a fan&#8230; a really big fan.</p>
      <p><strong>Welland Bubble</strong> &#8211; A term coined by Jay for Frank&#8217;s closed-mindedness and unwillingness to step outside his comfort zone (and also his reluctance to travel to Toronto more frequently).</p>
      <p><strong>Wet Noodle</strong> &#8211; A film that is unsatisfying or disappointing.</p>
      <p><strong>What a Peach</strong> &#8211; See: Peach.</p>
      <p><strong>Who is the Master?</strong> &#8211; A question posed by Sean in <a href="http://filmjunk.com/2012/09/18/film-junk-podcast-episode-386-the-master-and-tiff-2012/">Episode #386: The Master and TIFF 2012</a> in reference to the title of P.T. Anderson&#8217;s The Master. Sometimes brought up in jest when someone is reading too much into a film&#8217;s title or content.</p>
      <p><strong>Wintle</strong> &#8211; Friend of the show and former webmaster of The Horror Blog. Wintle has previously guested on the podcast and currently works at Sean&#8217;s place of employment. Best known for his appearance on <a href="http://filmjunk.com/2009/03/17/film-junk-podcast-episode-211-the-last-house-on-the-left/">Episode #211: The Last House on the Left</a>.</p>
      <p><strong>The Wire Stunt Casting</strong> &#8211; A recurring accusation Frank will randomly bestow upon movies that happen to star more than one former cast member of the HBO series The Wire. (see also: Stunt Casting)</p>
      <p><strong>Wonder Bread</strong> &#8211; In the early days of quarantine, Jay casually asked Frank what kind of bread he buys at the grocery store. Frank refused to answer, calling it &#8220;too personal&#8221;, which led Jay to assume that he must use Wonder Bread. To this day, it remains a running joke and unsolved mystery.</p>
      <p><strong>Skottie Young</strong> &#8211; Renowned comic book artist and writer who has become a friend of the show and occasional special guest. Known for Marvel&#8217;s Oz series and the new Rocket Raccoon ongoing series (among others).</p>
      <p><strong>Zak</strong> &#8211; Friend of the show and former co-host of Muzak for Cybernetics indie music podcast with Sean. Sometimes referred to as our &#8220;gay friend Zak&#8221; although he is not actually gay. Known for his love of mumblecore and Terrence Malick.</p>
      <p><strong>Rob Zombie</strong> &#8211; Horror-oriented musician and filmmaker that has been a highly debated figure on Film Junk over the years. Although the quality of his movies have often been questioned, Jay in particular has expressed a desire to just hang out with him because he seems like such a cool guy.</p>
   </div>
</template>

<style scoped>
   a {
      @apply text-blue-fj hover:opacity-80;
   }

   p {
      @apply mb-6;
   }

   .floatright {
      @apply float-right ml-5 mb-1;
   }

   .regularbuttondark {
      @apply py-1 px-2 rounded-full border border-blue-fj;
   }
</style>